### ISSUE TITLE
Investigate ????? reactions

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/DiscordDataParser#14]

**Comment by taahamahdi** [comment]
I looked for some custom emojis that were eventually deleted in my messages folder, but they had their original names, so it likely doesn't have anything to do with that.

**Comment by ChilliDoughnuts** [comment]
See #28 , maybe those emojis had Unicode characters?

**Comment by Brainicism** [comment]
Did a little bit of investigating and the `???` reactions seemed to be default discord emojis, and come from the backup itself rather than the parsed output.

**Comment by Brainicism** [comment]
Data provided by discord is returned as `???`, not as a result of the parser. Only solution is to either provide an explanation, or filter them out
