### ISSUE TITLE
Analyze "Message by Time of Day" but by the time at the local location and timezone it was sent from.  

### ISSUE THREAD

**Issue by ChilliDoughnuts** [Brainicism/DiscordDataParser#49]
For anyone that feel like messing with timezones and enjoy tearing their hair out.

This should be a seperate analysis from the current "Message by Time of Day".

As an example, let's say I send 5 messages.
"I love you" sent from 16:00 UTC-5 (21:00 UTC)
"Just kidding" sent from16:00 UTC-3 (19:00 UTC)
"Heyyyy" sent from 16:00 UTC-8 (00:00 UTC)
"Just chillin wbu" sent from 19:00 UTC-5 (00:00 UTC)
"I have a bf" sent from 19:00 UTC-2 (21:00 UTC)

The "Message by Time of Day" would count 2 of (21:00 UTC), 2 of (00:00 UTC), and 1 of (19:00 UTC).

What I am suggesting is for something to count 3 of (16:00 local) and 2 of (19:00 local).
This could be done by looking at the location that the message was sent from, then figuring out the local timezone from that.

Bonus points for looking at the date of the message and figuring out Daylight Savings and the many quirks of timezones.

This is relevant for co-op students and people that travel often.

**Comment by Brainicism** [comment]
Messages do not contain timezone information

**Comment by ChilliDoughnuts** [comment]
I looked at "Time spent by location" and for some reason falsely believed that the messages would contain information on where it was sent from.

**Comment by Brainicism** [comment]
The location data comes from `session_start` and `session_end` events, and it is not clear if the time ranges they cover account for every message sent. It would also be fairly difficult to do the mapping.
