### ISSUE TITLE
Add remaining information to index.html

### ISSUE THREAD

**Issue by Brainicism** [Brainicism/DiscordDataParser#7]
Information still being printed out to console

**Comment by ChilliDoughnuts** [comment]
What is meant by "remaining information"?

**Comment by Brainicism** [comment]
The information still being printed out in the console

**Comment by ChilliDoughnuts** [comment]
> -----------------------------------
> Total Messages: 258452
> Average words per sentence: 3.45
> Average messages per day: 438.05
> Most used message: ["oh", 5544]
> Most used word: ["i", 31645]
> Most active thread: ["general-1", 63814]
> 
> Activity Analysis 72.0s
> -----------------------------------
> Total Sessions: 7107
> Average session length: 42.8 minutes
> App opened 1883 times
> Total Reactions Added: 1901
> Total Reactions Removed: 101
> Total Voice Channels Joined: 1854

This information?

**Comment by Brainicism** [comment]
Correct. Removing any duplicate information already shown in the graphs
